source 'https://github.com/pengwenxin/CGSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TTAPIsKit_Example' do
  pod 'TTAPIsKit', :path => '../'

  target 'TTAPIsKit_Tests' do
    inherit! :search_paths

    
  end
end
